#!/usr/bin/env bash

##############################################################################
# Check if qasm is available
##############################################################################

if [ ! -f ../../M2M/QNICE/assembler/qasm ]; then
    echo ""
    echo "ERROR: QNICE assembler ../../M2M/QNICE/assembler/qasm not found."
    echo ""
    echo "Things to try:"
    echo "1. This repository has dependencies: Did you run"
    echo "       git submodule update --init --recursive"
    echo "   after cloning the repository? If not, run it now."
    echo ""
    echo "2. Build the QNICE toolchain. Answer all questions by pressing ENTER."
    echo "       cd ../../M2M/QNICE/tools"
    echo "       ./make-toolchain.sh"
    echo ""
    exit
fi;

##############################################################################
# C64 specific: Generate osm_const.asm
##############################################################################


{
    echo "; DO NOT MANUALLY EDIT"
    echo "; AUTOGENERATED BY ./make_rom.sh"
    echo "; These constants are equal to the menu indexes defined in"
    echo "; ../vhdl/mega65.vhd and in ../vhdl/config.vhd"
    echo ""
    echo "; -----------------------------------------------------------------"
    echo "; C64 specific OSM item constants"
    echo "; -----------------------------------------------------------------"
    echo ""
} > osm_const.asm

awk '/constant C_MENU_/ {gsub("C_MENU_", "C64_OSM_"); gsub(";", ""); printf("%-27s .EQU %s\n", $2, $6)}' ../vhdl/mega65.vhd >> osm_const.asm

{
    echo ""
    echo "; -----------------------------------------------------------------"
    echo "; C64 specific menu group items"
    echo "; -----------------------------------------------------------------"
    echo ""
} >> osm_const.asm

awk '/constant OPTM_G_/ && !/16#/ {gsub("OPTM_G_", "C64_OPTM_G_"); gsub(";", ""); printf("%-27s .EQU %s\n", $2, $6)}' ../vhdl/config.vhd >> osm_const.asm

##############################################################################
# M2M framework: Generate globals.asm
##############################################################################


{
    echo "; DO NOT MANUALLY EDIT"
    echo "; AUTOGENERATED BY ./make_rom.sh"
    echo "; These constants are taken from ../vhdl/globals.vhd"
    echo ""
} > globals.asm

awk '/constant C_VDNUM/ {gsub(/.*:=|;.*/, "", $0); split($0, a, " "); val=a[1]; if (val+0 == 0) val=1; printf("VDRIVES_MAX                 .EQU %s\n", val)}' ../vhdl/globals.vhd >> globals.asm
awk '/constant C_CRTROMS_MAN_NUM/ {gsub(/.*:=|;.*/, "", $0); split($0, a, " "); val=a[1]; if (val+0 == 0) val=1; printf("CRTROM_MAN_MAX              .EQU %s\n", val)}' ../vhdl/globals.vhd >> globals.asm
awk '/constant C_CRTROMS_AUTO_NUM/ {gsub(/.*:=|;.*/, "", $0); split($0, a, " "); val=a[1]; if (val+0 == 0) val=1; printf("CRTROM_AUT_MAX              .EQU %s\n", val)}' ../vhdl/globals.vhd >> globals.asm

# Export the .crt size ceiling = C_CRT_MAX_SIZE = (C_HMAP_CRT_GUARD - C_HMAP_CRT) windows
# * 8 KB, so the Shell (PREP_LOAD_IMAGE) enforces exactly the SIMCRT-pool size and can never
# drift from the HyperRAM map in globals.vhd when it is retuned.
crt_base=$(awk '/constant C_HMAP_CRT / {gsub(/.*:= *x"|".*/, "", $0); print $0}' ../vhdl/globals.vhd)
crt_top=$(awk '/constant C_HMAP_CRT_GUARD / {gsub(/.*:= *x"|".*/, "", $0); print $0}' ../vhdl/globals.vhd)
crt_max=$(( (0x${crt_top} - 0x${crt_base}) * 8192 ))
printf 'C64_CRT_MAX_SIZE_HI         .EQU 0x%04X\n' $(( (crt_max >> 16) & 0xFFFF )) >> globals.asm
printf 'C64_CRT_MAX_SIZE_LO         .EQU 0x%04X\n' $((  crt_max        & 0xFFFF )) >> globals.asm

##############################################################################
# M2M framework: Generate shell_fhandles.asm
##############################################################################

{
    echo "; DO NOT MANUALLY EDIT"
    echo "; AUTOGENERATED BY ./make_rom.sh"
    echo "; These file handles are generated based on VDRIVES_MAX and CRTROM_MAN_MAX"
    echo ""
} > shell_fhandles.asm

vdrives_max=$(awk '/constant C_VDNUM/ {gsub(/.*:=|;.*/, "", $0); split($0, a, " "); print a[1]}' ../vhdl/globals.vhd)
crtrom_man_max=$(awk '/constant C_CRTROMS_MAN_NUM/ {gsub(/.*:=|;.*/, "", $0); split($0, a, " "); print a[1]}' ../vhdl/globals.vhd)

if [ $vdrives_max -eq 0 ]; then vdrives_max=1; fi
if [ $crtrom_man_max -eq 0 ]; then crtrom_man_max=1; fi

for ((i=1; i<=vdrives_max; i++))
do
    echo "HANDLE_VD_FILE$i    .BLOCK  FAT32\$FDH_STRUCT_SIZE"
done >> shell_fhandles.asm

for ((i=1; i<=crtrom_man_max; i++))
do
    echo "HANDLE_RM_FILE$i    .BLOCK  FAT32\$FDH_STRUCT_SIZE"
done >> shell_fhandles.asm

##############################################################################
# M2M framework: Generate shell_fh_ptrs.asm
##############################################################################

{
    echo "; DO NOT MANUALLY EDIT"
    echo "; AUTOGENERATED BY ./make_rom.sh"
    echo "; These are pointers to the file handles for the virtual drives and manually loadable CRTs/ROMs"
    echo ""
} > shell_fh_ptrs.asm

print_file_handles() {
    local label=$1
    local pointer_name=$2
    local count=$3

    printf "%-20s .DW  " "$label" >> shell_fh_ptrs.asm
    for ((i=1;i<=count;i++)); do
        printf "%s%d" "$pointer_name" $i >> shell_fh_ptrs.asm
        if (( i % 3 == 0 && i < count )); then
            printf ",\n%-20s .DW  " " " >> shell_fh_ptrs.asm
        elif (( i % 3 != 0 && i < count )); then
            printf ", " >> shell_fh_ptrs.asm
        fi
    done
    printf "\n" >> shell_fh_ptrs.asm
}

# Generate shell_fh_ptrs.asm
print_file_handles "HNDL_VD_FILES" "HANDLE_VD_FILE" $vdrives_max
print_file_handles "HNDL_RM_FILES" "HANDLE_RM_FILE" $crtrom_man_max

##############################################################################
# M2M framework: Assemble and generate various output files:
#   m2m-rom.def: QNICE Monitor operating system calls
#   m2m-rom.lis: List file containing the complete listing & assembled code
#   m2m-rom.out: File that can be loaded in the QNICE Monitor using M/L
#   m2m-rom.rom: Vivado ROM compatible 16-bit binary
##############################################################################

../../M2M/QNICE/assembler/asm m2m-rom.asm
ASM_RC=$?

##############################################################################
# Guard the Shell-ROM budget. QNICE reserves 0x7000-0x7FFF for memory-mapped
# I/O, so the usable ROM is 0x0000-0x6FFF = 28672 words. The assembler does NOT
# check this; an overflow would otherwise fail obscurely later (in Vivado). The
# m2m-rom.rom holds exactly one 16-bit word (binary) per line.
##############################################################################
ROM_MAX_WORDS=28672

# The asm wrapper deletes m2m-rom.rom up front and only regenerates it on success,
# so a missing .rom (or a non-zero exit) means assembly failed -- fail the build
# loudly instead of silently skipping the size guard and exiting 0.
if [ "$ASM_RC" -ne 0 ] || [ ! -f m2m-rom.rom ]; then
    echo "ERROR: assembling m2m-rom.asm failed (asm exit ${ASM_RC}); m2m-rom.rom was not produced."
    exit 1
fi

ROM_WORDS=$(wc -l < m2m-rom.rom | tr -d ' ')
if [ "$ROM_WORDS" -gt "$ROM_MAX_WORDS" ]; then
    echo "ERROR: m2m-rom.rom is ${ROM_WORDS} words, exceeds the ${ROM_MAX_WORDS}-word"
    echo "       Shell-ROM budget (0x0000-0x6FFF; 0x7000+ is QNICE MMIO)."
    exit 1
fi
echo "Shell ROM: ${ROM_WORDS}/${ROM_MAX_WORDS} words."
