; ****************************************************************************
; MiSTer2MEGA65 (M2M) QNICE ROM
;
; Testbed for the pure menu structure algorithms in menu_struct.asm:
; OPTM_STRUCT_BUILD, OPTM_STRUCT_VAL and OPTM_SUMM_SCAN.
;
; Runs headlessly in the QNICE emulator. The fixtures and the expected
; output traces are generated by menu_test.py; run the whole suite with:
;     python3 menu_test.py run
;
; The testbed only DUMPS results; all checking happens in menu_test.py by
; comparing the dump against the independently computed golden trace.
;
; done by sy2002 in 2026 and licensed under GPL v3
; ****************************************************************************

#include "../../QNICE/dist_kit/sysdef.asm"
#include "../../QNICE/dist_kit/monitor.def"

                .ORG    0x8000

                MOVE    ST_S_BEGIN, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                ; ------------------------------------------------------------
                ; Structure fixtures: validation + builds at every level
                ; ------------------------------------------------------------

                MOVE    ST_FXIDX, R8            ; fixture counter := 0
                MOVE    0, @R8

_ST_FX_LOOP     MOVE    ST_FXIDX, R8
                MOVE    @R8, R0                 ; R0: fixture index
                CMP     FXT_CNT, R0             ; all fixtures done?
                RBRA    _ST_SUM_INIT, Z         ; yes: summary fixtures

                MOVE    ST_S_FX, R8             ; print "FX <idx>"
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

                MOVE    FXT_TAB, R1             ; R1: fixture data pointer
                ADD     R0, R1
                MOVE    @R1, R1
                MOVE    ST_START, R8            ; unpack start index
                MOVE    @R1++, @R8
                MOVE    ST_N, R8                ; unpack item count
                MOVE    @R1++, @R8
                MOVE    ST_GROUPS, R8           ; unpack groups pointer
                MOVE    R1, @R8

                ; validation
                MOVE    ST_GROUPS, R8
                MOVE    @R8, R8
                MOVE    ST_N, R9
                MOVE    @R9, R9
                MOVE    ST_START, R10
                MOVE    @R10, R10
                RSUB    OPTM_STRUCT_VAL, 1
                RBRA    _ST_V_OK, !C

                MOVE    R9, R0                  ; print "V ERR C=<c> I=<i>"
                MOVE    R10, R1
                MOVE    ST_S_VERR, R8
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                MOVE    ST_S_I, R8
                SYSCALL(puts, 1)
                MOVE    R1, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)
                MOVE    ST_LASTLVL, R8          ; on error: only build L=0
                MOVE    0, @R8
                RBRA    _ST_B_INIT, 1

_ST_V_OK        MOVE    R9, R0                  ; print "V OK R=<r> H=<h>"
                MOVE    R10, R1
                MOVE    ST_S_VOK, R8
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                MOVE    ST_S_H, R8
                SYSCALL(puts, 1)
                MOVE    R1, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)
                MOVE    ST_LASTLVL, R8          ; build L = 0 .. regions
                MOVE    R0, @R8

                ; builds at every level
_ST_B_INIT      MOVE    ST_LVL, R8
                MOVE    0, @R8

_ST_B_LOOP      MOVE    ST_S_BL, R8             ; print "B L=<level>"
                SYSCALL(puts, 1)
                MOVE    ST_LVL, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)

                MOVE    ST_BUF, R8              ; build into the buffer
                MOVE    ST_N, R9
                MOVE    @R9, R9
                MOVE    ST_GROUPS, R10
                MOVE    @R10, R10
                MOVE    ST_LVL, R11
                MOVE    @R11, R11
                RSUB    OPTM_STRUCT_BUILD, 1
                RBRA    _ST_B_OK, !C

                MOVE    R10, R0                 ; print " ERR I=<idx>"
                MOVE    ST_S_ERRI, R8
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)
                RBRA    _ST_B_NEXT, 1

_ST_B_OK        MOVE    R9, R0                  ; print " C=<vis>"
                MOVE    R10, R1
                MOVE    R11, R2
                MOVE    ST_S_C, R8
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                MOVE    ST_S_P, R8              ; print " P=<parent>"
                SYSCALL(puts, 1)
                MOVE    R1, R8
                SYSCALL(puthex, 1)
                MOVE    ST_S_O, R8              ; print " O=<opener>"
                SYSCALL(puts, 1)
                MOVE    R2, R8
                SYSCALL(puthex, 1)
                MOVE    ST_S_W, R8              ; print " W=" + the words
                SYSCALL(puts, 1)
                MOVE    ST_BUF, R0
                ADD     1, R0                   ; skip the size word
                MOVE    ST_N, R1
                MOVE    @R1, R1
_ST_B_WORDS     MOVE    ST_S_SP, R8
                SYSCALL(puts, 1)
                MOVE    @R0++, R8
                SYSCALL(puthex, 1)
                SUB     1, R1
                RBRA    _ST_B_WORDS, !Z
                SYSCALL(crlf, 1)

_ST_B_NEXT      MOVE    ST_LVL, R8              ; next level
                ADD     1, @R8
                MOVE    ST_LASTLVL, R9
                MOVE    @R9, R9
                CMP     @R8, R9                 ; level <= last level?
                RBRA    _ST_B_LOOP, !N

                MOVE    ST_FXIDX, R8            ; next fixture
                ADD     1, @R8
                RBRA    _ST_FX_LOOP, 1

                ; ------------------------------------------------------------
                ; Summary scan fixtures
                ; ------------------------------------------------------------

_ST_SUM_INIT    MOVE    ST_FXIDX, R8
                MOVE    0, @R8

_ST_SUM_LOOP    MOVE    ST_FXIDX, R8
                MOVE    @R8, R0                 ; R0: fixture index
                CMP     SUM_CNT, R0             ; all fixtures done?
                RBRA    _ST_DONE, Z             ; yes

                MOVE    ST_S_S, R8              ; print "S <idx>"
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)

                MOVE    SUM_TAB, R1             ; R1: fixture data pointer
                ADD     R0, R1
                MOVE    @R1, R1
                MOVE    @R1++, R2               ; R2: heading index
                MOVE    @R1++, R3               ; R3: item count
                MOVE    R1, R4                  ; R4: groups array
                MOVE    R1, R5                  ; R5: stdsel array
                ADD     R3, R5

                MOVE    R4, R8                  ; R8: ptr to heading word
                ADD     R2, R8
                MOVE    R4, R9                  ; R9: end-of-menu sentinel
                ADD     R3, R9
                MOVE    R5, R10                 ; R10: stdsel array
                MOVE    R4, R11                 ; R11: groups array base
                RSUB    OPTM_SUMM_SCAN, 1
                RBRA    _ST_SUM_FND, C

                MOVE    R8, R0                  ; print " ERR C=<class>"
                MOVE    ST_S_SERR, R8
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)
                RBRA    _ST_SUM_NEXT, 1

_ST_SUM_FND     SUB     R4, R8                  ; pointer to flat index
                MOVE    R8, R0
                MOVE    ST_S_FND, R8            ; print " FOUND I=<idx>"
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

_ST_SUM_NEXT    MOVE    ST_FXIDX, R8
                ADD     1, @R8
                RBRA    _ST_SUM_LOOP, 1

_ST_DONE        MOVE    ST_S_DONE, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)
                SYSCALL(exit, 1)

; ----------------------------------------------------------------------------
; Strings and variables
; ----------------------------------------------------------------------------

ST_S_BEGIN      .ASCII_W "== BEGIN =="
ST_S_FX         .ASCII_W "FX "
ST_S_VOK        .ASCII_W "V OK R="
ST_S_VERR       .ASCII_W "V ERR C="
ST_S_H          .ASCII_W " H="
ST_S_I          .ASCII_W " I="
ST_S_BL         .ASCII_W "B L="
ST_S_ERRI       .ASCII_W " ERR I="
ST_S_C          .ASCII_W " C="
ST_S_P          .ASCII_W " P="
ST_S_O          .ASCII_W " O="
ST_S_W          .ASCII_W " W="
ST_S_SP         .ASCII_W " "
ST_S_S          .ASCII_W "S "
ST_S_FND        .ASCII_W " FOUND I="
ST_S_SERR       .ASCII_W " ERR C="
ST_S_DONE       .ASCII_W "DONE"

; the component under test (menu.asm includes menu_struct.asm)
#include "../menu.asm"
#include "../menu_vars.asm"

; generated fixtures
#include "menu_test_fixtures.asm"

ST_FXIDX        .BLOCK 1
ST_START        .BLOCK 1
ST_N            .BLOCK 1
ST_GROUPS       .BLOCK 1
ST_LVL          .BLOCK 1
ST_LASTLVL      .BLOCK 1
ST_BUF          .BLOCK 256
