; ****************************************************************************
; MiSTer2MEGA65 (M2M) QNICE ROM
;
; Equivalence harness: the no-breaking-changes regression gate for the
; M2M V2.1.0 bracket parser (see doc/path-to-OSM-submenus.md section 4.3
; in the C64MEGA65 repository).
;
; Contains a verbatim copy of the pre-V2.1.0 three-pass toggle parser
; (_OLDSTR, copied from menu.asm as of M2M V2.0.0 with renamed labels) and
; runs it side by side with the new _OPTM_STRUCT over legacy-shaped fixtures
; (including the complete pre-V6 C64 menu and 150 seeded-random legacy
; configurations) at every menu level. The structure arrays and the visible
; line counts must match word for word.
;
; Fixtures are generated by menu_test.py; run the whole suite with:
;     python3 menu_test.py run
;
; done by sy2002 in 2026 and licensed under GPL v3
; ****************************************************************************

#include "../../QNICE/dist_kit/sysdef.asm"
#include "../../QNICE/dist_kit/monitor.def"

                .ORG    0x8000

                MOVE    EQ_S_BEGIN, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                ; minimal initialization record: the parsers only use the
                ; groups array pointer and the fatal callback
                MOVE    OPTM_DATA, R8
                MOVE    EQ_REC, @R8
                MOVE    EQ_REC, R8
                ADD     OPTM_CLBK_FATAL, R8
                MOVE    EQ_FATAL, @R8

                MOVE    EQ_FXIDX, R8            ; fixture counter := 0
                MOVE    0, @R8

_EQ_FX_LOOP     MOVE    EQ_FXIDX, R8
                MOVE    @R8, R0                 ; R0: fixture index
                CMP     EQV_CNT, R0             ; all fixtures done?
                RBRA    _EQ_DONE, Z             ; yes

                MOVE    EQV_TAB, R1             ; R1: fixture data pointer
                ADD     R0, R1
                MOVE    @R1, R1
                MOVE    EQ_N, R8                ; unpack item count
                MOVE    @R1++, @R8
                MOVE    EQ_LASTLVL, R8          ; unpack region count
                MOVE    @R1++, @R8
                MOVE    EQ_REC, R8              ; record: groups pointer
                ADD     OPTM_IR_GROUPS, R8
                MOVE    R1, @R8

                MOVE    EQ_LVL, R8              ; level := 0
                MOVE    0, @R8

_EQ_LVL_LOOP    MOVE    OPTM_MENULEVEL, R8      ; set the level under test
                MOVE    EQ_LVL, R9
                MOVE    @R9, @R8

                MOVE    EQ_BUF_OLD, R8          ; run the old toggle parser
                MOVE    EQ_N, R9
                MOVE    @R9, R9
                RSUB    _OLDSTR, 1
                MOVE    EQ_CNT_OLD, R8
                MOVE    R9, @R8

                MOVE    EQ_BUF_NEW, R8          ; run the new bracket parser
                MOVE    EQ_N, R9
                MOVE    @R9, R9
                RSUB    _OPTM_STRUCT, 1
                MOVE    EQ_CNT_NEW, R8
                MOVE    R9, @R8

                MOVE    EQ_S_E, R8              ; print "E <fixture> L=<lvl>"
                SYSCALL(puts, 1)
                MOVE    EQ_FXIDX, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)
                MOVE    EQ_S_L, R8
                SYSCALL(puts, 1)
                MOVE    EQ_LVL, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)

                ; compare the visible counts and the arrays word for word
                ; (including the size word at index 0)
                MOVE    EQ_CNT_OLD, R8
                MOVE    EQ_CNT_NEW, R9
                MOVE    @R8, R8
                CMP     R8, @R9
                RBRA    _EQ_FAIL, !Z

                MOVE    EQ_BUF_OLD, R0
                MOVE    EQ_BUF_NEW, R1
                MOVE    EQ_N, R2
                MOVE    @R2, R2
                ADD     1, R2                   ; include the size word
_EQ_CMP_LOOP    CMP     @R0++, @R1++
                RBRA    _EQ_FAIL, !Z
                SUB     1, R2
                RBRA    _EQ_CMP_LOOP, !Z

                MOVE    EQ_S_OK, R8             ; print " OK"
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)
                RBRA    _EQ_LVL_NEXT, 1

_EQ_FAIL        MOVE    EQ_S_FAIL, R8           ; print " FAIL" + both arrays
                SYSCALL(puts, 1)
                MOVE    EQ_BUF_OLD, R0
                RSUB    _EQ_DUMP, 1
                MOVE    EQ_BUF_NEW, R0
                RSUB    _EQ_DUMP, 1
                SYSCALL(crlf, 1)

_EQ_LVL_NEXT    MOVE    EQ_LVL, R8              ; next level
                ADD     1, @R8
                MOVE    EQ_LASTLVL, R9
                MOVE    @R9, R9
                CMP     @R8, R9                 ; level <= region count?
                RBRA    _EQ_LVL_LOOP, !N        ; yes: next level

                MOVE    EQ_FXIDX, R8            ; next fixture
                ADD     1, @R8
                RBRA    _EQ_FX_LOOP, 1

_EQ_DONE        MOVE    EQ_S_DONE, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)
                SYSCALL(exit, 1)

                ; dump the array at R0 (size word + entries) as hex words
_EQ_DUMP        INCRB
                MOVE    R0, R1
                MOVE    EQ_N, R2
                MOVE    @R2, R2
                ADD     1, R2
_EQ_DUMP_LOOP   MOVE    EQ_S_SP, R8
                SYSCALL(puts, 1)
                MOVE    @R1++, R8
                SYSCALL(puthex, 1)
                SUB     1, R2
                RBRA    _EQ_DUMP_LOOP, !Z
                MOVE    EQ_S_BAR, R8
                SYSCALL(puts, 1)
                DECRB
                RET

                ; fatal callback: must never fire for legacy-shaped fixtures
EQ_FATAL        MOVE    R9, R0
                MOVE    EQ_S_F, R8
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)
                SYSCALL(exit, 1)

; ----------------------------------------------------------------------------
; The pre-V2.1.0 three-pass toggle parser, verbatim from menu.asm (M2M
; V2.0.0, labels renamed _OPTM_STRUCT* -> _OLDSTR*). Do not modernize: this
; copy IS the reference implementation that the new parser must reproduce
; bit-identically on every legacy-shaped config.
; ----------------------------------------------------------------------------

_OLDSTR         INCRB

                MOVE    R8, R0                  ; R0: current array element
                MOVE    R9, R1                  ; R1: amount of menu items
                MOVE    OPTM_DATA, R2           ; R2: OPTM_IR_GROUPS array
                MOVE    @R2, R2
                ADD     OPTM_IR_GROUPS, R2
                MOVE    @R2, R2
                XOR     R3, R3                  ; R3: current main/submen id
                MOVE    1, R4                   ; R4: next submen id
                XOR     R5, R5                  ; R5: submenu region flag

                MOVE    R1, @R0++               ; 1st element = size

_OLDSTR_1       MOVE    @R2++, R6               ; R6: next menu group item
                AND     OPTM_SUBMENU, R6        ; check for submenu marker
                RBRA    _OLDSTR_3, Z            ; jump, if no submenu marker

                CMP     1, R5                   ; are we already in a region?
                RBRA    _OLDSTR_2, Z            ; yes: jump
                MOVE    1, R5                   ; no: set region flag
                MOVE    R4, R3                  ; current submen id = next..
                ADD     1, R4                   ; ..submen id and inc. next
                RBRA    _OLDSTR_3, 1            ; continue with storing

_OLDSTR_2       MOVE    R3, @R0++               ; store item in struct array
                XOR     R5, R5                  ; clear region flag
                XOR     R3, R3                  ; current id = main menu
                RBRA    _OLDSTR_4, 1            ; continue with next iteration

_OLDSTR_3       MOVE    R3, @R0++               ; store item in struct array
_OLDSTR_4       SUB     1, R1                   ; more menu items?
                RBRA    _OLDSTR_1, !Z           ; yes: loop

                CMP     1, R5                   ; no: region cntr still actve?
                RBRA    _OLDSTR_C, !Z           ; no: all good: continue
                MOVE    OPTM_CLBK_FATAL, R7     ; yes: fatal
                MOVE    OPTM_F_MENUSUB, R8
                XOR     R9, R9
                RBRA    _OPTM_CALL, 1           ; RBRA because of fatal

_OLDSTR_C       MOVE    R9, R0                  ; R0: size of menu (#items)
                MOVE    R8, R1                  ; R1: current array entry
                ADD     1, R1                   ; skip size information
                MOVE    OPTM_MENULEVEL, R3      ; R3: current menu level
                MOVE    @R3, R3
                XOR     R7, R7                  ; R7: count active menu items

_OLDSTR_5       CMP     R3, @R1                 ; are we in the curr. men. lvl
                RBRA    _OLDSTR_7, Z            ; yes: set to 1 and next entry
_OLDSTR_6       AND     0x7FFF, @R1++           ; no: highest bit = 0 and next
                RBRA    _OLDSTR_8, 1
_OLDSTR_7       OR      0x8000, @R1++           ; active itm: highest bit to 1
                ADD     1, R7                   ; one more active item
_OLDSTR_8       SUB     1, R0                   ; more entries?
                RBRA    _OLDSTR_5, !Z           ; yes: iterate

                MOVE    R9, R4                  ; R4: preserve overall amount
                MOVE    R7, R9                  ; return amount of active itms

                XOR     R1, R1                  ; R1: last menu number
                MOVE    1, R5                   ; R5: first occurance flag
                MOVE    R8, R7                  ; R7: ptr. to curr. itm in lst
                ADD     1, R7                   ; skip size info
_OLDSTR_9       MOVE    @R7, R6
                AND     0x00FF, R6
                CMP     R1, R6                  ; last menu number changed?
                RBRA    _OLDSTR_10, Z           ; no
                MOVE    R6, R1                  ; yes: store this num as last
                MOVE    1, R5                   ; set first occurance flag

_OLDSTR_10      MOVE    @R7, R6
                AND     0x8000, R6              ; part of current list?
                RBRA    _OLDSTR_11, !Z          ; yes

                CMP     0, R3                   ; are we in the main menu?
                RBRA    _OLDSTR_12, !Z          ; no
                CMP     1, R5                   ; yes: and is it first ocurr.?
                RBRA    _OLDSTR_12, !Z          ; no
                XOR     R5, R5                  ; yes: delete flag and..
                OR      0x8000, @R7             ; ..make it part of the list
                ADD     1, R9                   ; one more active item
                RBRA    _OLDSTR_12, 1

_OLDSTR_11      CMP     0, R3                   ; are we in the main menu?
                RBRA    _OLDSTR_12, Z           ; yes: move on
                CMP     1, R5                   ; no: and is it first ocurr.?
                RBRA    _OLDSTR_12, !Z          ; no
                XOR     R5, R5                  ; yes: delete flag and..
                AND     0x7FFF, @R7             ; ..remove it from the list
                SUB     1, R9                   ; one less active item

_OLDSTR_12      ADD     1, R7                   ; next list element
                SUB     1, R4                   ; one less item to process
                RBRA    _OLDSTR_9, !Z

                DECRB
                RET

; ----------------------------------------------------------------------------
; Strings and variables
; ----------------------------------------------------------------------------

EQ_S_BEGIN      .ASCII_W "== BEGIN =="
EQ_S_E          .ASCII_W "E "
EQ_S_L          .ASCII_W " L="
EQ_S_OK         .ASCII_W " OK"
EQ_S_FAIL       .ASCII_W " FAIL"
EQ_S_SP         .ASCII_W " "
EQ_S_BAR        .ASCII_W " |"
EQ_S_F          .ASCII_W "F C="
EQ_S_DONE       .ASCII_W "DONE"

; the component under test (menu.asm includes menu_struct.asm)
#include "../menu.asm"
#include "../menu_vars.asm"

; generated fixtures
#include "menu_equiv_fixtures.asm"

EQ_FXIDX        .BLOCK 1
EQ_N            .BLOCK 1
EQ_LVL          .BLOCK 1
EQ_LASTLVL      .BLOCK 1
EQ_CNT_OLD      .BLOCK 1
EQ_CNT_NEW      .BLOCK 1
EQ_REC          .BLOCK 19
EQ_BUF_OLD      .BLOCK 256
EQ_BUF_NEW      .BLOCK 256
