; ****************************************************************************
; MiSTer2MEGA65 (M2M) QNICE ROM
;
; Navigation testbed: drives the full OPTM_RUN state machine of menu.asm
; through the complete V6 (#189) C64 menu using a scripted key sequence.
; All screen output functions of the initialization record are stubbed; the
; scripted OPTM_FP_GETKEY prints one trace line per call:
;
;     K L=<menu level> C=<cursor flat index> P=<parent id> O=<opener index>
;
; the selection callback prints  S G=<group word> I=<item> K=<key>,  and
; each return of OPTM_RUN prints  R C=<cursor>.  Some script entries carry
; bit 15: the stub then simulates a background redraw (OPTM_SHOW +
; OPTM_SELECT, like the vdrive status redraws in options.asm) before
; returning the key.
;
; This covers: entering nested submenus (depth 2), leaving them via the
; closer line and via Run/Stop (one level per press), the enter cursor
; scan, cursor wrap-around within a nested view, radio and single-select
; semantics, and menu-level persistence across OPTM_RUN invocations.
;
; The script, the menu image and the expected trace are generated by
; menu_test.py; run the whole suite with:
;     python3 menu_test.py run
;
; done by sy2002 in 2026 and licensed under GPL v3
; ****************************************************************************

#include "../../QNICE/dist_kit/sysdef.asm"
#include "../../QNICE/dist_kit/monitor.def"

                .ORG    0x8000

                MOVE    NT_S_BEGIN, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                ; copy the default selected-state array into RAM (the menu
                ; modifies it) and zero-initialize the lines array
                MOVE    NAV_STDSEL_DEF, R0
                MOVE    NT_STDSEL, R1
                MOVE    NT_LINES, R2
                MOVE    NAV_N, R3
_NT_CPY         MOVE    @R0++, @R1++
                MOVE    0, @R2++
                SUB     1, R3
                RBRA    _NT_CPY, !Z

                MOVE    NT_SCEN, R8             ; scenario counter := 0
                MOVE    0, @R8
                MOVE    NT_SCRIPT_POS, R8       ; script position := 0
                MOVE    NAV_SCRIPT, @R8
                MOVE    NT_SCRIPT_END, R8
                MOVE    NAV_SCRIPT, R9
                ADD     NAV_SCRIPT_CNT, R9
                MOVE    R9, @R8

                MOVE    NT_REC, R8              ; initialize the menu
                MOVE    0, R9                   ; x
                MOVE    0, R10                  ; y
                MOVE    30, R11                 ; dx
                MOVE    30, R12                 ; dy
                RSUB    OPTM_INIT, 1

                MOVE    NT_CURSOR, R8           ; cursor := start item
                MOVE    NAV_START, @R8

                ; run the menu; re-run it after each close while script
                ; entries are left (tests menu level persistence). Like
                ; HELP_MENU in production, draw the menu via OPTM_SHOW
                ; before running it: this exercises the %s machinery at
                ; the current (possibly persisted) menu level
_NT_RUN         RSUB    OPTM_SHOW, 1
                MOVE    NT_CURSOR, R8
                MOVE    @R8, R8
                RSUB    OPTM_RUN, 1
                MOVE    NT_CURSOR, R9           ; remember returned cursor
                MOVE    R8, @R9

                MOVE    NT_S_R, R8              ; print "R C=<cursor>"
                SYSCALL(puts, 1)
                MOVE    NT_CURSOR, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

                MOVE    NT_SCRIPT_POS, R8       ; script exhausted?
                MOVE    @R8, R8
                MOVE    NT_SCRIPT_END, R9
                CMP     R8, @R9
                RBRA    _NT_RUN, !Z             ; no: run the menu again

                ; ------------------------------------------------------------
                ; Advance to the next scenario:
                ;  2 = synthetic menu covering the enter-scan stop positions
                ;      the V6 menu cannot provide (a region whose first content
                ;      is a nested child opener and an empty region)
                ;  3 = dependency menu covering the live OPTM_RUN dependency
                ;      paths: the enter-scan dependency skip and the real-time
                ;      redraw on a mother toggle
                ; (see nav2_script() / nav3_script() in menu_test.py)
                ; ------------------------------------------------------------

                MOVE    NT_SCEN, R8
                ADD     1, @R8
                MOVE    @R8, R0                 ; R0: scenario number
                CMP     1, R0
                RBRA    _NT_SCEN2, Z
                CMP     2, R0
                RBRA    _NT_SCEN3, Z
                RBRA    _NT_DONE, 1             ; all scenarios done

_NT_SCEN2       MOVE    NT_S_N2, R8            ; print the scenario marker
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                MOVE    NAV2_STDSEL_DEF, R0     ; selected-state defaults
                MOVE    NT_STDSEL, R1
                MOVE    NAV2_N, R3
_NT_CPY2        MOVE    @R0++, @R1++
                SUB     1, R3
                RBRA    _NT_CPY2, !Z

                MOVE    NT_REC, R8              ; repoint the init record
                ADD     OPTM_IR_SIZE, R8
                MOVE    NAV2_N, @R8
                MOVE    NT_REC, R8
                ADD     OPTM_IR_ITEMS, R8
                MOVE    NAV2_ITEMS, @R8
                MOVE    NT_REC, R8
                ADD     OPTM_IR_GROUPS, R8
                MOVE    NAV2_GROUPS, @R8

                MOVE    NT_SCRIPT_POS, R8       ; switch to script 2
                MOVE    NAV2_SCRIPT, @R8
                MOVE    NT_SCRIPT_END, R8
                MOVE    NAV2_SCRIPT, R9
                ADD     NAV2_SCRIPT_CNT, R9
                MOVE    R9, @R8

                MOVE    NT_REC, R8              ; re-initialize like a boot
                MOVE    0, R9
                MOVE    0, R10
                MOVE    30, R11
                MOVE    30, R12
                RSUB    OPTM_INIT, 1

                MOVE    NT_CURSOR, R8           ; cursor := start item
                MOVE    NAV2_START, @R8
                RBRA    _NT_RUN, 1

_NT_SCEN3       MOVE    NT_S_N3, R8            ; print the scenario marker
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                MOVE    NAV3_STDSEL_DEF, R0     ; selected-state defaults
                MOVE    NT_STDSEL, R1
                MOVE    NAV3_N, R3
_NT_CPY3        MOVE    @R0++, @R1++
                SUB     1, R3
                RBRA    _NT_CPY3, !Z

                MOVE    NT_REC, R8              ; repoint the init record and
                ADD     OPTM_IR_SIZE, R8        ; turn the dependency feature ON
                MOVE    NAV3_N, @R8             ; by pointing OPTM_IR_DEPS at the
                MOVE    NT_REC, R8              ; resolved array
                ADD     OPTM_IR_ITEMS, R8
                MOVE    NAV3_ITEMS, @R8
                MOVE    NT_REC, R8
                ADD     OPTM_IR_GROUPS, R8
                MOVE    NAV3_GROUPS, @R8
                MOVE    NT_REC, R8
                ADD     OPTM_IR_DEPS, R8
                MOVE    NAV3_DEPS, @R8

                MOVE    NT_SCRIPT_POS, R8       ; switch to script 3
                MOVE    NAV3_SCRIPT, @R8
                MOVE    NT_SCRIPT_END, R8
                MOVE    NAV3_SCRIPT, R9
                ADD     NAV3_SCRIPT_CNT, R9
                MOVE    R9, @R8

                MOVE    NT_REC, R8              ; re-initialize like a boot
                MOVE    0, R9
                MOVE    0, R10
                MOVE    30, R11
                MOVE    30, R12
                RSUB    OPTM_INIT, 1

                MOVE    NT_CURSOR, R8           ; cursor := start item
                MOVE    NAV3_START, @R8
                RBRA    _NT_RUN, 1

_NT_DONE        MOVE    NT_S_DONE, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)
                SYSCALL(exit, 1)

; ----------------------------------------------------------------------------
; Initialization record: stubbed screen functions, scripted key feed
; ----------------------------------------------------------------------------

NT_REC          .DW     NT_STUB, NT_STUB, NT_STUB, NT_STUB
                .DW     NT_STUB, NT_STUB, NT_GETKEY
                .DW     NT_CB_SEL, NT_CB_SHOW, NT_FATAL
                .DW     0x0078, 0, 0x0078, 0    ; sel. chars (inline strings)
                .DW     NAV_N, NAV_ITEMS, NAV_GROUPS, NT_STDSEL, NT_LINES, 0
                                                ; last word = OPTM_IR_DEPS: 0 =
                                                ; dependency feature off here

                ; all visual functions: do nothing, preserve all registers
NT_STUB         RET

                ; scripted OPTM_FP_GETKEY: print the state trace, optionally
                ; simulate a background redraw, return the next key in R8
NT_GETKEY       INCRB

                MOVE    NT_S_K, R8              ; "K L="
                SYSCALL(puts, 1)
                MOVE    OPTM_MENULEVEL, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)
                MOVE    NT_S_C, R8              ; " C="
                SYSCALL(puts, 1)
                MOVE    OPTM_CUR_SEL, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)
                MOVE    NT_S_P, R8              ; " P="
                SYSCALL(puts, 1)
                MOVE    OPTM_LVL_PARENT, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)
                MOVE    NT_S_O, R8              ; " O="
                SYSCALL(puts, 1)
                MOVE    OPTM_LVL_OPENER, R8
                MOVE    @R8, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

                MOVE    NT_SCRIPT_POS, R0       ; script exhausted?
                MOVE    @R0, R1
                MOVE    NT_SCRIPT_END, R2
                MOVE    @R2, R2
                CMP     R1, R2
                RBRA    _NT_GK_1, !Z
                MOVE    NT_S_X, R8              ; yes: should not happen:
                SYSCALL(puts, 1)                ; print "X" and force close
                SYSCALL(crlf, 1)
                MOVE    OPTM_KEY_CLOSE, R8
                RBRA    _NT_GK_RET, 1

_NT_GK_1        MOVE    @R1, R2                 ; R2: next script word
                ADD     1, @R0                  ; advance the script

                MOVE    R2, R3
                AND     0x8000, R3              ; redraw marker?
                RBRA    _NT_GK_2, Z             ; no

                RSUB    OPTM_SHOW, 1            ; simulate the background
                MOVE    OPTM_CUR_SEL, R8        ; redraw exactly like the
                MOVE    @R8, R8                 ; vdrive status change in
                MOVE    OPTM_SEL_SEL, R9        ; options.asm does it
                RSUB    OPTM_SELECT, 1

_NT_GK_2        MOVE    R2, R8                  ; return the key
                AND     0x7FFF, R8

_NT_GK_RET      DECRB
                RET

                ; %s callback: OPTM_SHOW calls this for every line that
                ; contains a %s and that is visible at the current menu
                ; level; print the flat line index and return the string
                ; unchanged (no replacement). The W trace lines verify that
                ; the %s scanner of OPTM_SHOW keeps its line counter in
                ; sync, also across labels whose last character is a
                ; percent sign (" 100%" and friends)
NT_CB_SHOW      INCRB
                MOVE    R8, R0                  ; preserve the string ptr
                MOVE    R9, R1                  ; preserve the line index

                MOVE    NT_S_W, R8              ; "W I="
                SYSCALL(puts, 1)
                MOVE    R1, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

                MOVE    R0, R8                  ; return string unchanged
                MOVE    R1, R9
                DECRB
                RET

                ; selection callback: print the group word, the item index
                ; within the group and the key that selected it
NT_CB_SEL       INCRB
                MOVE    R8, R0
                MOVE    R9, R1
                MOVE    R10, R2

                MOVE    NT_S_S, R8              ; "S G="
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                MOVE    NT_S_I, R8              ; " I="
                SYSCALL(puts, 1)
                MOVE    R1, R8
                SYSCALL(puthex, 1)
                MOVE    NT_S_KY, R8             ; " K="
                SYSCALL(puts, 1)
                MOVE    R2, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

                MOVE    R0, R8
                MOVE    R1, R9
                MOVE    R2, R10
                DECRB
                RET

                ; fatal callback: print the error code and stop
NT_FATAL        MOVE    R9, R0
                MOVE    NT_S_F, R8
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)
                SYSCALL(exit, 1)

; ----------------------------------------------------------------------------
; Strings and variables
; ----------------------------------------------------------------------------

NT_S_BEGIN      .ASCII_W "== BEGIN =="
NT_S_K          .ASCII_W "K L="
NT_S_C          .ASCII_W " C="
NT_S_P          .ASCII_W " P="
NT_S_O          .ASCII_W " O="
NT_S_S          .ASCII_W "S G="
NT_S_I          .ASCII_W " I="
NT_S_KY         .ASCII_W " K="
NT_S_R          .ASCII_W "R C="
NT_S_F          .ASCII_W "F C="
NT_S_X          .ASCII_W "X"
NT_S_W          .ASCII_W "W I="
NT_S_N2         .ASCII_W "N2"
NT_S_N3         .ASCII_W "N3"
NT_S_DONE       .ASCII_W "DONE"

; the component under test (menu.asm includes menu_struct.asm)
#include "../menu.asm"
#include "../menu_vars.asm"

; generated menu image and key script
#include "menu_nav_fixtures.asm"

NT_SCRIPT_POS   .BLOCK 1
NT_SCRIPT_END   .BLOCK 1
NT_SCEN         .BLOCK 1
NT_CURSOR       .BLOCK 1
NT_STDSEL       .BLOCK 256
NT_LINES        .BLOCK 256
