; ****************************************************************************
; MiSTer2MEGA65 (M2M) QNICE ROM
;
; Testbed for the smart-dependencies routines in optm_deps.asm:
; OPTM_DEPS_RESOLVE, OPTM_DEPS_VAL and the runtime predicate OPTM_DEP_OK
; (exercised through OPTM_STRUCT_BUILD and OPTM_SUMM_SCAN).
;
; Runs headlessly in the QNICE emulator. The fixtures and the expected output
; traces are generated by menu_test.py; run the whole suite with:
;     python3 menu_test.py run
;
; The testbed only DUMPS results; all checking happens in menu_test.py by
; comparing the dump against the independently computed golden trace.
;
; done by sy2002 in 2026 and licensed under GPL v3
; ****************************************************************************

#include "../../QNICE/dist_kit/sysdef.asm"
#include "../../QNICE/dist_kit/monitor.def"

                .ORG    0x8000

                MOVE    DT_S_BEGIN, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                ; ------------------------------------------------------------
                ; #5 regression pin: OPTM_DEPS_VAL must leave R8 unchanged on
                ; the success path (its documented contract). Run it on the
                ; valid fixture 0 with R8 = a sentinel and check R8 survived.
                ; ------------------------------------------------------------
                MOVE    DV_TAB, R1
                MOVE    @R1, R1
                MOVE    @R1++, R2              ; R2: N
                MOVE    R1, R3                ; R3: groups (the sentinel)
                MOVE    R1, R4                ; R4: raw deps
                ADD     R2, R4
                MOVE    R4, R5                ; R5: special
                ADD     R2, R5
                MOVE    R3, R8                ; R8: sentinel = groups pointer
                MOVE    R2, R9
                MOVE    R4, R10
                MOVE    R5, R11
                RSUB    OPTM_DEPS_VAL, 1
                CMP     R8, R3                ; R8 preserved across the call?
                RBRA    _DT_P8_BAD, !Z
                MOVE    DT_S_P8OK, R8
                RBRA    _DT_P8_PR, 1
_DT_P8_BAD      MOVE    DT_S_P8BAD, R8
_DT_P8_PR       SYSCALL(puts, 1)
                SYSCALL(crlf, 1)

                ; ------------------------------------------------------------
                ; Resolution: raw dependency words -> resolved words
                ; ------------------------------------------------------------

                MOVE    DT_FXIDX, R8
                MOVE    0, @R8
_DT_R_LOOP      MOVE    DT_FXIDX, R8
                MOVE    @R8, R0                 ; R0: fixture index
                CMP     DR_CNT, R0
                RBRA    _DT_V_INIT, Z

                MOVE    DR_TAB, R1             ; R1: fixture block pointer
                ADD     R0, R1
                MOVE    @R1, R1
                MOVE    @R1++, R2              ; R2: amount of items (N)
                MOVE    R1, R3                ; R3: groups array
                MOVE    R1, R4                ; R4: raw dependency array
                ADD     R2, R4

                MOVE    R4, R5                ; copy raw deps into the buffer
                MOVE    DT_BUF, R6
                MOVE    R2, R7
_DT_R_CPY       MOVE    @R5++, @R6++
                SUB     1, R7
                RBRA    _DT_R_CPY, !Z

                MOVE    DT_BUF, R8            ; resolve in place
                MOVE    R3, R9
                MOVE    R2, R10
                RSUB    OPTM_DEPS_RESOLVE, 1

                MOVE    DT_S_R, R8           ; print "R <idx> W=" + words
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                MOVE    DT_S_W, R8
                SYSCALL(puts, 1)
                MOVE    DT_BUF, R0
                MOVE    R2, R1
_DT_R_DUMP      MOVE    DT_S_SP, R8
                SYSCALL(puts, 1)
                MOVE    @R0++, R8
                SYSCALL(puthex, 1)
                SUB     1, R1
                RBRA    _DT_R_DUMP, !Z
                SYSCALL(crlf, 1)

                MOVE    DT_FXIDX, R8
                ADD     1, @R8
                RBRA    _DT_R_LOOP, 1

                ; ------------------------------------------------------------
                ; Validation: the five fatal classes plus the valid case
                ; ------------------------------------------------------------

_DT_V_INIT      MOVE    DT_FXIDX, R8
                MOVE    0, @R8
_DT_V_LOOP      MOVE    DT_FXIDX, R8
                MOVE    @R8, R0
                CMP     DV_CNT, R0
                RBRA    _DT_B_INIT, Z

                MOVE    DV_TAB, R1
                ADD     R0, R1
                MOVE    @R1, R1
                MOVE    @R1++, R2             ; R2: N
                MOVE    R1, R3               ; R3: groups
                MOVE    R1, R4               ; R4: raw deps
                ADD     R2, R4
                MOVE    R4, R5               ; R5: special array
                ADD     R2, R5

                MOVE    DT_S_V, R8           ; print "V <idx>"
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)

                MOVE    R3, R8               ; validate
                MOVE    R2, R9
                MOVE    R4, R10
                MOVE    R5, R11
                RSUB    OPTM_DEPS_VAL, 1
                RBRA    _DT_V_ERR, C

                MOVE    DT_S_OK, R8          ; print " OK"
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)
                RBRA    _DT_V_NEXT, 1

_DT_V_ERR       MOVE    R9, R6               ; print " ERR C=<class> I=<idx>"
                MOVE    R10, R7
                MOVE    DT_S_ERR, R8
                SYSCALL(puts, 1)
                MOVE    R6, R8
                SYSCALL(puthex, 1)
                MOVE    DT_S_I, R8
                SYSCALL(puts, 1)
                MOVE    R7, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

_DT_V_NEXT      MOVE    DT_FXIDX, R8
                ADD     1, @R8
                RBRA    _DT_V_LOOP, 1

                ; ------------------------------------------------------------
                ; Builder with the dependency predicate (OPTM_DEP_OK):
                ; visibility at a level for given selected states
                ; ------------------------------------------------------------

_DT_B_INIT      MOVE    OPTM_DATA, R8         ; the predicate reads the init
                MOVE    DT_REC, @R8           ; record via OPTM_DATA

                MOVE    DT_FXIDX, R8
                MOVE    0, @R8
_DT_B_LOOP      MOVE    DT_FXIDX, R8
                MOVE    @R8, R0
                CMP     DB_CNT, R0
                RBRA    _DT_S_INIT, Z

                MOVE    DB_TAB, R1
                ADD     R0, R1
                MOVE    @R1, R1
                MOVE    @R1++, R2            ; R2: N
                MOVE    @R1++, R3           ; R3: level
                MOVE    R1, R4             ; R4: groups
                MOVE    R1, R5             ; R5: resolved deps
                ADD     R2, R5
                MOVE    R5, R6             ; R6: stdsel
                ADD     R2, R6

                MOVE    DT_REC, R8         ; point the record at this fixture;
                ADD     OPTM_IR_DEPS, R8   ; since dependency format 2 the
                MOVE    R5, @R8            ; predicate also reads the groups
                MOVE    DT_REC, R8         ; array and the menu size from the
                ADD     OPTM_IR_STDSEL, R8 ; record (to find the mother type
                MOVE    R6, @R8            ; and to walk the mother group)
                MOVE    DT_REC, R8
                ADD     OPTM_IR_GROUPS, R8
                MOVE    R4, @R8
                MOVE    DT_REC, R8
                ADD     OPTM_IR_SIZE, R8
                MOVE    R2, @R8

                MOVE    DT_BUF, R8         ; build the structure at the level
                MOVE    R2, R9
                MOVE    R4, R10
                MOVE    R3, R11
                RSUB    OPTM_STRUCT_BUILD, 1

                MOVE    R9, R7             ; R7: visible count
                MOVE    DT_S_B, R8         ; print "B <idx> C=<vis> W=" + words
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)
                MOVE    DT_S_C, R8
                SYSCALL(puts, 1)
                MOVE    R7, R8
                SYSCALL(puthex, 1)
                MOVE    DT_S_W, R8
                SYSCALL(puts, 1)
                MOVE    DT_BUF, R0
                ADD     1, R0              ; skip the size word
                MOVE    R2, R1
_DT_B_DUMP      MOVE    DT_S_SP, R8
                SYSCALL(puts, 1)
                MOVE    @R0++, R8
                SYSCALL(puthex, 1)
                SUB     1, R1
                RBRA    _DT_B_DUMP, !Z
                SYSCALL(crlf, 1)

                MOVE    DT_FXIDX, R8
                ADD     1, @R8
                RBRA    _DT_B_LOOP, 1

                ; ------------------------------------------------------------
                ; %s summary walk with the dependency predicate
                ; ------------------------------------------------------------

_DT_S_INIT      MOVE    DT_FXIDX, R8
                MOVE    0, @R8
_DT_S_LOOP      MOVE    DT_FXIDX, R8
                MOVE    @R8, R0
                CMP     DS_CNT, R0
                RBRA    _DT_DONE, Z

                MOVE    DS_TAB, R1
                ADD     R0, R1
                MOVE    @R1, R1
                MOVE    @R1++, R2          ; R2: N
                MOVE    @R1++, R3         ; R3: heading index
                MOVE    R1, R4           ; R4: groups
                MOVE    R1, R5           ; R5: resolved deps
                ADD     R2, R5
                MOVE    R5, R6           ; R6: stdsel
                ADD     R2, R6

                MOVE    DT_REC, R8       ; point the record at this fixture
                ADD     OPTM_IR_DEPS, R8 ; (incl. groups + size, see above)
                MOVE    R5, @R8
                MOVE    DT_REC, R8
                ADD     OPTM_IR_STDSEL, R8
                MOVE    R6, @R8
                MOVE    DT_REC, R8
                ADD     OPTM_IR_GROUPS, R8
                MOVE    R4, @R8
                MOVE    DT_REC, R8
                ADD     OPTM_IR_SIZE, R8
                MOVE    R2, @R8

                MOVE    DT_S_D, R8       ; print "D <idx>"
                SYSCALL(puts, 1)
                MOVE    R0, R8
                SYSCALL(puthex, 1)

                MOVE    R4, R8           ; R8: pointer to heading word
                ADD     R3, R8
                MOVE    R4, R9           ; R9: end-of-menu sentinel
                ADD     R2, R9
                MOVE    R6, R10          ; R10: stdsel array
                MOVE    R4, R11          ; R11: groups array base
                RSUB    OPTM_SUMM_SCAN, 1
                RBRA    _DT_S_FND, C

                MOVE    R8, R7           ; print " ERR C=<class>"
                MOVE    DT_S_ERRC, R8
                SYSCALL(puts, 1)
                MOVE    R7, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)
                RBRA    _DT_S_NEXT, 1

_DT_S_FND       SUB     R4, R8           ; R8: flat index of the found line
                MOVE    R8, R7
                MOVE    DT_S_FND, R8     ; print " FOUND I=<idx>"
                SYSCALL(puts, 1)
                MOVE    R7, R8
                SYSCALL(puthex, 1)
                SYSCALL(crlf, 1)

_DT_S_NEXT      MOVE    DT_FXIDX, R8
                ADD     1, @R8
                RBRA    _DT_S_LOOP, 1

_DT_DONE        MOVE    DT_S_DONE, R8
                SYSCALL(puts, 1)
                SYSCALL(crlf, 1)
                SYSCALL(exit, 1)

; ----------------------------------------------------------------------------
; Strings and variables
; ----------------------------------------------------------------------------

DT_S_BEGIN      .ASCII_W "== BEGIN =="
DT_S_P8OK       .ASCII_W "P8 OK"
DT_S_P8BAD      .ASCII_W "P8 BAD"
DT_S_R          .ASCII_W "R "
DT_S_V          .ASCII_W "V "
DT_S_B          .ASCII_W "B "
DT_S_D          .ASCII_W "D "
DT_S_W          .ASCII_W " W="
DT_S_C          .ASCII_W " C="
DT_S_OK         .ASCII_W " OK"
DT_S_ERR        .ASCII_W " ERR C="
DT_S_ERRC       .ASCII_W " ERR C="
DT_S_I          .ASCII_W " I="
DT_S_FND        .ASCII_W " FOUND I="
DT_S_SP         .ASCII_W " "
DT_S_DONE       .ASCII_W "DONE"

; the component under test (menu.asm includes menu_struct.asm + optm_deps.asm)
#include "../menu.asm"
#include "../menu_vars.asm"

; generated fixtures
#include "optm_deps_fixtures.asm"

DT_FXIDX        .BLOCK 1
DT_REC          .BLOCK 20
DT_BUF          .BLOCK 256                      ; fits the V6 menu fixtures
